config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  get "/admins/log_out" => "admin_sessions#destroy", :as => "log_out"
  get "/admins/log_in" => "admin_sessions#new", :as => "log_in"
  get "/admins/sign_up" => "admins#new", :as => "sign_up"
  get "/admins/home" => "hospitals#index", :as => "admin_home"

  get "/admins/ambulance_users" => "ambulance_users#index", :as => :ambulance_users
  get "/admins/ambulance_users/add" => "ambulance_users#new", :as => :ambulance_user_add
  post "/admins/ambulance_users" => "ambulance_users#create"
  get "/admins/ambulance_users/:id" => "ambulance_users#show", :as => :ambulance_user
  get "/admins/ambulance_users/:id/edit" => "ambulance_users#edit", :as => :ambulance_user_edit
  patch "/admins/ambulance_users/:id/" => "ambulance_users#update"
  put "/admins/ambulance_users/:id/" => "ambulance_users#update"
  delete "/admins/ambulance_users/:id/" => "ambulance_users#destroy"

  get "/hospital_super_users/log_out" => "hospital_super_user_sessions#destroy", :as => "hospital_super_user_log_out"
  get "/hospital_super_users/log_in" => "hospital_super_user_sessions#new", :as => "hospital_super_user_log_in"
  get "/admins/hospital_super_users/add" => "hospital_super_users#new", :as => :hospital_super_user_add
  post "/admins/hospital_super_users/add" => "hospital_super_users#create"
  get "/super_users/home" => "hospital_super_users#index", :as => "hospital_super_user_home"

  get "/log_out" => "manager_sessions#destroy", :as => "manager_log_out"
  get "/log_in" => "manager_sessions#new", :as => "manager_log_in"
  get "/super_users/managers/add" => "managers#new", :as => :manager_add
  post "/super_users/managers/add" => "managers#create"
  get "/beds" => "managers#index", :as => "manager_beds"

  get "/super_users/beds" => "beds#index", :as => :beds
  get "/super_users/beds/add" => "beds#new", :as => :bed_add
  post "/super_users/beds/" => "beds#create"
  get "/super_users/beds/:id" => "beds#show", :as => :bed
  get "/super_users/beds/:id/edit" => "beds#edit", :as => :bed_edit
  patch "/super_users/beds/:id/" => "beds#update"
  put "/super_users/beds/:id/" => "beds#update"
  delete "/super_users/beds/:id/" => "beds#destroy"

  get "/" => "requests#index", :as => "root"
  get "/requests/accepted" => "requests#accepted", :as => "requests_accepted"
  get "/requests/completed" => "requests#completed", :as => "requests_completed"
  get "/requests/user_location" => "requests#user_location", :as => "user_location"

  get "/requests/:id" => "requests#show", :as => :request_show
  patch "/requests/:id" => "requests#update"
  put "/requests/:id" => "requests#update_details"
  

  resources :hospitals, :path => "/admin/hospitals"
  resources :patients, :path => "/admin/patients"

  resources :admins
  resources :admin_sessions

  resources :hospital_super_users
  resources :hospital_super_user_sessions

  resources :managers
  resources :manager_sessions
  
  
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get "/hospitals" => "ambulance_users#get_nearby_hospitals"
      get "/request_status" => "requests#request_status"
      post "/request_complete" => "requests#request_complete"

      resources :sessions, only: [:create, :destroy]
      resources :ambulance_users, only: [:show]
      resources :requests, only: [:index, :create, :show, :update, :destroy]
      resources :request_details, only: [:index, :create, :show, :update, :destroy]

    end
  end  

  

end

app/views/partials/_admin_nav.html.erb
	<!-- Navigation -->
	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="<%= admin_home_path %>">Life Saver - Admin</a>
		</div>
		<!-- Top Menu Items -->
		<ul class="nav navbar-right top-nav">
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> <%= current_admin.name %> <b class="caret"></b></a>
				<ul class="dropdown-menu">
					<!-- <li>
						<a href="#"><i class="fa fa-fw fa-user"></i> Profile</a>
					</li>
					<li>
						<a href="#"><i class="fa fa-fw fa-gear"></i> Settings</a>
					</li>
					<li class="divider"></li> -->
					<li>
						<% if is_admin_logged_in %>
						<%= link_to log_out_path do %> <%= content_tag :i, "", :class => "fa fa-fw fa-power-off" %>Log Out <% end %>
						<% end %>
					</li>
				</ul>
			</li>
		</ul>
		<!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
		<div class="collapse navbar-collapse navbar-ex1-collapse">
			<ul class="nav navbar-nav side-nav">
				<li class="<%= is_active?(admin_home_path) %>">
					<a href="<%= admin_home_path %>"><i class="fa fa-fw fa-edit"></i> Hospitals</a>
				</li>
				<li class="<%= is_active?(new_hospital_path) %>">
					<a href='<%= new_hospital_path %>' ><i class="fa fa-fw fa-bar-chart-o"></i> Add Hospital</a>

				</li>
				<li class="<%= is_active?(hospital_super_user_add_path) %>">
					<a href="<%= hospital_super_user_add_path %>"><i class="fa fa-fw fa-desktop"></i> Add Superusers</a>
				</li>
				<li class="<%= is_active?(patients_path) %>">
					<a href="<%= patients_path %>"><i class="fa fa-fw fa-table"></i> Patients</a>
				</li>
				<li class="<%= is_active?(new_patient_path) %>">
					<a href="<%= new_patient_path %>"><i class="fa fa-fw fa-table"></i> Add Patient</a>
				</li>
				<li class="<%= is_active?(ambulance_users_path) %>">
					<a href="<%= ambulance_users_path %>"><i class="fa fa-fw fa-dashboard"></i> Ambulance Users</a>
				</li>
				<li class="<%= is_active?(ambulance_user_add_path) %>">
					<a href="<%= ambulance_user_add_path %>"><i class="fa fa-fw fa-desktop"></i> Add Ambulance User</a>
				</li>				
			</ul>
		</div>
		<!-- /.navbar-collapse -->
	</nav>

app/views/partials/_alerts.html.erb
  <% flash.each do |name, msg| %>
  <%= content_tag :div, msg, class: [:alert, alert_for(name)] %>
  <% end %>

app/views/partials/_ambulance_user_add.html.erb
		<h2>Add Ambulance User</h2>

		<%= simple_form_for @ambulance_user, html: { class: 'form-horizontal', multipart: true } do |f| %>
		<div class="form-group">
			<%= f.input :email %>
		</div>
		<div class="form-group text-center">
			<%= f.input :name %>
		</div>
		<div class="form-group text-center">
			<%= f.input :belongs_to %>
		</div>
		<div class="form-group text-center">
			<%= f.input :password %>
		</div>
		<div class="form-group text-center">
			<%= f.input :password_confirmation %>
		</div>
		<div class="form-group text-center">
			<%= f.button :submit, class: 'btn-success' %>
		</div>
		<% end %>

app/views/partials/_ambulance_user_edit.html.erb
<div class="form-wrapper">
  <%= render 'partials/ambulance_user_form'  %>
</div>

<div class="text-center edit-links">
  <%= link_to "Delete ambulance user", ambulance_user_path(@ambulance_user), method: :delete, data: { confirm: "Are you sure you want to delete this ambulance user?" } %>
  |
  <%= link_to "cancel", admin_home_path %>
</div>

app/views/partials/_ambulance_user_show.html.erb
<div class="ambulance_user-wrapper row">
  <div class="ambulance_user">
    <div class="ambulance_user-head">
      <div class="name text-center">
        <%= @ambulance_user.name %>
      </div>
    </div>
    <div class="text-center">
      <%= @ambulance_user.belongs_to %>
    </div>
    <div class="text-center">
      <%= @ambulance_user.email %>
    </div>
    <div class="text-center edit-links">
      <%= link_to "Cancel", admin_home_path %>
      |
      <%= link_to "Edit Ambulance User", ambulance_user_edit_path(@ambulance_user) %>
    </div>

    <div class="text-center">
      <%= link_to "Cancel", admin_home_path %>
    </div>
  </div>
</div>

app/views/partials/_ambulance_users.html.erb
<% @ambulance_users.each do |ambulance_user| -%>
<div class="row">
	<a href="<%= ambulance_user_path(ambulance_user) %>">
		<div class="col-md-4" align="center">
			<%= ambulance_user.email %>
		</div>
		<div class="col-md-4" align="center">
			<%= ambulance_user.name %>
		</div>
		<div class="col-md-4" align="center">
			<%= ambulance_user.belongs_to %>
		</div>
	</a>
</div>
<hr>
<% end -%>

app/views/partials/_beds_form.html.erb
		<h2>Add a Bed</h2>

		<%= simple_form_for @bed, html: { class: 'form-horizontal', multipart: true } do |f| %>
		<div class="form-group text-center">
			<%= f.input :name %>
		</div>
		<div class="form-group text-center">
			<%= f.button :submit, class: 'btn-success' %>
		</div>
		<% end %>

app/views/partials/_edit_patient.html.erb
<div class="form-wrapper">
  <%= render 'partials/patientform'  %>
</div>

<div class="text-center edit-links">
  <%= link_to "Delete patient", patient_path(@patient), method: :delete, data: { confirm: "Are you sure you want to delete this patient?" } %>
  |
  <%= link_to "cancel", patients_path %>
</div>

app/views/partials/_hospitalform.html.erb
<%= simple_form_for @hospital, html: { class: 'form-horizontal', multipart: true } do |f| %>
    <div class="form-group">
      <%= f.input :logo %>
    </div>
    <div class="form-group text-center">
      <%= f.input :name %>
    </div>
    <div class="form-group text-center">
      <%= f.input :address %>
    </div>
    <div class="form-group text-center">
      <%= f.button :submit, class: 'btn-success' %>
    </div>
<% end %>

app/views/partials/_hospitals.html.erb
<% @hospitals.each_slice(4) do |slice| %>
<div class="row">
	<% slice.each do |hospital| -%>
	<div class="col-md-3">
		<div class="hospital">
			<div class="hospital-head">
				<div class="name">
					<%= hospital.name %>
				</div>
			</div>
			<div class="image center-block">
				<%= link_to (image_tag hospital.logo.url(:medium), class:'img-responsive'), hospital_path(hospital) %>
			</div>
		</div>
	</div>
	<% end -%>
</div>
<% end -%>

app/views/partials/_manager_nav.html.erb
	<!-- Navigation -->
	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="<%= root_path %>">Life Saver - Manager</a>
		</div>
		<!-- Top Menu Items -->
		<ul class="nav navbar-right top-nav">
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> <%= current_manager.user_name %> <b class="caret"></b></a>
				<ul class="dropdown-menu">
					<!-- <li>
						<a href="#"><i class="fa fa-fw fa-user"></i> Profile</a>
					</li>
					<li>
						<a href="#"><i class="fa fa-fw fa-gear"></i> Settings</a>
					</li>
					<li class="divider"></li> -->
					<li>
						<% if is_manager_logged_in %>
						<%= link_to manager_log_out_path do %> <%= content_tag :i, "", :class => "fa fa-fw fa-power-off" %>Log Out <% end %>
						<% end %>
					</li>
				</ul>
			</li>
		</ul>
		<!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
		<div class="collapse navbar-collapse navbar-ex1-collapse">
			<ul class="nav navbar-nav side-nav">
				
				<li class="<%= is_active?(root_path) %>">
					<a href='<%= root_path %>' ><i class="fa fa-fw fa-bar-chart-o"></i> Incoming Requests</a>

				</li>
				<li class="<%= is_active?(requests_accepted_path) %>">
					<a href='<%= requests_accepted_path %>' ><i class="fa fa-fw fa-bar-chart-o"></i> Accepted Requests</a>

				</li>
				<li class="<%= is_active?(requests_completed_path) %>">
					<a href='<%= requests_completed_path %>' ><i class="fa fa-fw fa-bar-chart-o"></i> Completed Requests</a>

				</li>
				
				<li class="<%= is_active?(manager_beds_path) %>">
					<a href="<%= manager_beds_path %>"><i class="fa fa-fw fa-edit"></i> Beds</a>
				</li>
				
			</ul>
		</div>
		<!-- /.navbar-collapse -->
	</nav>

app/views/partials/_patientform.html.erb
<%= simple_form_for @patient, html: { class: 'form-horizontal', multipart: true } do |f| %>
    <div class="form-group text-center">
      <%= f.input :cnic %>
    </div>
    <div class="form-group text-center">
      <%= f.button :submit, class: 'btn-success' %>
    </div>
<% end %>

app/views/partials/_show_patient.html.erb
<div class="patients-wrapper row">
  <div class="patient" align="center">
    <div class="patient-head">
      <div class="name">
        <%= @patient.id %>
      </div>
    </div>
    <div class="cnic center-block">
      <%= @patient.cnic %>
    </div>
    
    <div class="text-center edit-links">
      <%= link_to "Cancel", admin_home_path %>
      |
      <%= link_to "Edit patient", edit_patient_path(@patient) %>
    </div>

    <div class="text-center">
      <%= link_to "Cancel", admin_home_path %>
    </div>
  </div>
</div>

app/views/partials/_super_user_nav.html.erb
	<!-- Navigation -->
	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="<%= hospital_super_user_home_path %>">Life Saver - Super User</a>
		</div>
		<!-- Top Menu Items -->
		<ul class="nav navbar-right top-nav">
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> <%= current_hospital_super_user.user_name %> <b class="caret"></b></a>
				<ul class="dropdown-menu">
					<li>
						<a href="#"><i class="fa fa-fw fa-user"></i> Profile</a>
					</li>
					<li>
						<a href="#"><i class="fa fa-fw fa-gear"></i> Settings</a>
					</li>
					<li class="divider"></li>
					<li>
						<% if is_hospital_super_user_logged_in %>
						<%= link_to hospital_super_user_log_out_path do %> <%= content_tag :i, "", :class => "fa fa-fw fa-power-off" %>Log Out <% end %>
						<% end %>
					</li>
				</ul>
			</li>
		</ul>
		<!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
		<div class="collapse navbar-collapse navbar-ex1-collapse">
			<ul class="nav navbar-nav side-nav">
				<li class="<%= is_active?(hospital_super_user_home_path) %>">
					<a href="<%= hospital_super_user_home_path %>"><i class="fa fa-fw fa-edit"></i> Managers</a>
				</li>
				<li class="<%= is_active?(manager_add_path) %>">
					<a href='<%= manager_add_path %>' ><i class="fa fa-fw fa-bar-chart-o"></i> Add Manager</a>
				</li>	
				<li class="<%= is_active?(beds_path) %>">
					<a href="<%= beds_path %>"><i class="fa fa-fw fa-edit"></i> Beds</a>
				</li>
				<li class="<%= is_active?(bed_add_path) %>">
					<a href='<%= bed_add_path %>' ><i class="fa fa-fw fa-bar-chart-o"></i> Add Bed</a>
				</li>			
			</ul>
		</div>
		<!-- /.navbar-collapse -->
	</nav>